export const UPDATE_ATRIBUTOS = 'UPDATE_ATRIBUTOS'
export const FIRE_ATRIBUTOS = 'FIRE_ATRIBUTOS'
export const LOAD_ATRIBUTOS = 'LOAD_ATRIBUTOS'

export const UPDATE_PERICIAS = 'UPDATE_PERICIAS'
export const FIRE_PERICIAS = 'FIRE_PERICIAS'
export const LOAD_PERICIAS = 'LOAD_PERICIAS'